version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: kliksutin_dev
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    container_name: kliksutin_dev

volumes:
  pg_data:
