version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: ipsutin_dev
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 8000:8000
    container_name: ipsutin_dev

  db:
    image: postgres:16.3
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
    container_name: ipsutin_db

  redis:
    image: redis:7-alpine
    container_name: ipsutin_redis

volumes:
  pg_data:
  node_modules: