name: Deploy to staging

on:
  push:
    branches:
      - master

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build-and-push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: kliksutin
          tags: staging ${{ github.sha }}
          containerfiles: |
            ./Dockerfile

      - name: Push to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-and-push.outputs.image }}
          tags: ${{ steps.build-and-push.outputs.tags }}
          registry: quay.io/toska
          username: toska+github
          password: ${{ secrets.QUAY_IO_TOKEN }}
