name: E2E Tests

on: push

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project for eslint
        run: npm install
      - name: Run eslint
        run: npm run lint
